# Generated by Django 3.2.25 on 2025-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 9:35', '8:00 - 9:35'), ('9:50 - 11:25', '9:50 - 11:25'), ('11:55 - 13:30', '11:55 - 13:30'), ('13:45 - 15:20', '13:45 - 15:20'), ('15:50 - 17:25', '15:50 - 17:25')], default='11:30 - 12:30', max_length=50),
        ),
    ]
