# Generated by Django 3.2.25 on 2025-11-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('lab', 'Лабораторная работа'), ('practice', 'Практическое занятие'), ('seminar', 'Семинар')], default='lecture', max_length=15, verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Лекционная'), ('computer', 'Компьютерный класс'), ('seminar', 'Семинарская')], default='general', max_length=15, verbose_name='Тип аудитории'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Номер предмета'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='SchedulerApp.Instructor', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_numb_students',
            field=models.CharField(max_length=65, verbose_name='Макс. количество студентов'),
        ),
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='SchedulerApp.Course', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=50, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя преподавателя'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='uid',
            field=models.CharField(max_length=6, verbose_name='ID преподавателя'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ID времени'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 9:35', '8:00 - 9:35'), ('9:50 - 11:25', '9:50 - 11:25'), ('11:55 - 13:30', '11:55 - 13:30'), ('13:45 - 15:20', '13:45 - 15:20'), ('15:50 - 17:25', '15:50 - 17:25')], default='8:00 - 9:35', max_length=50, verbose_name='Время занятия'),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_number',
            field=models.CharField(max_length=6, verbose_name='Номер аудитории'),
        ),
        migrations.AlterField(
            model_name='room',
            name='seating_capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meeting_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime', verbose_name='Время занятия'),
        ),
        migrations.AlterField(
            model_name='section',
            name='num_class_in_week',
            field=models.IntegerField(default=0, verbose_name='Количество занятий в неделю'),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='ID секции'),
        ),
    ]
