# Generated by Django 3.2.25 on 2025-11-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_auto_20251114_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='SchedulerApp.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_numb_students',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='SchedulerApp.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='uid',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:45 - 9:45', '8:45 - 9:45'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:15 - 3:15', '2:15 - 3:15')], default='11:30 - 12:30', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meeting_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime'),
        ),
        migrations.AlterField(
            model_name='section',
            name='num_class_in_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
