# Generated by Django 3.2.25 on 2025-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_auto_20251116_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Laboratory'), ('Practice', 'Practice'), ('Seminar', 'Seminar')], default='Lecture', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lecture', 'Lecture Hall'), ('Computer Lab', 'Computer Lab'), ('Practice', 'Practice Room'), ('Seminar', 'Seminar Room')], default='Lecture', max_length=20),
        ),
    ]
